### PR TITLE
fix: remove lodash usage and types

### LINKED ISSUE #431: Error: Cannot find module 'lodash'
Lodash isn't listed in the `package.json` dependencies and is resulting in the following error:

```
Error: Cannot find module 'lodash'
Require stack:
- /home/icholy/src/github.com/my_project/node_modules/casbin/lib/cjs/frontend.js
- /home/icholy/src/github.com/my_project/node_modules/casbin/lib/cjs/index.js
```

Looks like it was removed here: https://github.com/casbin/node-casbin/commit/293a852803d5e83562a36bc35cdf48def0f0088b

### PR DESCRIPTION
**Pull request by icholy**
Fixes #431

### CODE REVIEW

**Comment by hsluoyz** [comment]
@icholy plz fix CI:

image

File: src/frontend.ts [hunk 1]
```diff
@@ -53,7 +52,7 @@ export async function casbinJsGetPermissionForUser(e: Enforcer, user?: string):
     item.unshift('g');
   });
 
-  obj['p'] = concat(policy, groupPolicy);
+  obj['p'] = [].concat(policy, groupPolicy);
```
Comment (nodece) [inline src/frontend.ts:55]:
```suggestion
  obj['p'] = [...policy, ...groupPolicy]
```

**Review by nodece — APPROVED** [review]

**Comment by nodece** [comment]
LGTM, good work @icholy
